version: '3'
services:
  portainer:
    image: portainer/portainer-ee
    container_name: portainer-ee
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data/:/data

volumes:
  portainer_data:
    driver: local